version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:latest
    environment:
      AIRFLOW_HOME: /usr/local/airflow
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    ports:
      - "8080:8080"
    command: ["airflow", "webserver"]
    volumes:
      - ./airflow:/usr/local/airflow
    depends_on:
      - airflow-init
    networks:
      - airflow_network

  airflow-scheduler:
    image: apache/airflow:latest
    environment:
      AIRFLOW_HOME: /usr/local/airflow
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: ["airflow", "scheduler"]
    volumes:
      - ./airflow:/usr/local/airflow
    depends_on:
      - airflow-init
    networks:
      - airflow_network

  airflow-init:
    image: apache/airflow:latest
    environment:
      AIRFLOW_HOME: /usr/local/airflow
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./airflow:/usr/local/airflow
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "airflow db init && \
       airflow users create -u admin -p admin -f admin -l user -r Admin -e joaovictormagalhaessouza@gmail.com"
    depends_on:
      - postgres
    networks:
      - airflow_network

networks:
  airflow_network:

volumes:
  postgres_data:
